// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nftolxkrheympzgslmdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mdG9seGtyaGV5bXB6Z3NsbWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzA2NTYsImV4cCI6MjA3MDQwNjY1Nn0.sYwjYvXTlCCqWZY_099gEzbIHT6KLrCEaxnzraR6554";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});